### ISSUE TITLE
Why is not possible to download data after july ? 

### ISSUE THREAD

**Issue by ryarca** [RamiKrispin/covid19Italy#14]

**Comment by RamiKrispin** [comment]
Hi @ryarca 

After installing the package from CRAN, to keep the data up-to-date, you should use the `update_data` function:

```
library(covid19italy)
update_data()
```

This function should sync with the package repository and check for updates, if updates are available it will reinstall the package from the repo. Once the update is done, the data on your local package will be up-to-date with the most recent data. 


Let me know if you having any issue with refreshing the data.
