### ISSUE TITLE
Detailed death counts per hospitalization/confinement?

### ISSUE THREAD

**Issue by psyguy** [RamiKrispin/covid19Italy#6]
Hi,

I'm fascinated by the clean data you've shared, especially with the distinction you make between hospitalization/confinement status of the active cases. However, the cumulative death toll is reported regardless of the hospitalization status of the patients.

That's very interesting info and can be used to estimate the difference in case fatality ratio of patients with different hospitalization statuses and give a hint about how hospitalization decisions (home confinement, in a regular hospital bed, or in ICU) are made across Italy.

Is that data available, and will it be added to the package/repo any time soon?

**Comment by RamiKrispin** [comment]
Hi @psyguy 

Unfortunately, currently, this data is not available on the raw data published by the Department of Civil Protection in Italy. If any additional data will be available, I will be happy to add it to the package in the future.

Best,
Rami
